# Site settings
title: Abhishek Bhattacharjee
email: abhishek.bhattacharjee11@gmail.com
description: "Who is John Galt? | About Me"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
