# Site settings
title: Abhishek Bhattacharjee
email: abhishek.bhattacharjee11@gmail.com
description: "Who is John Galt? | [About Me](http://abhishekbhattacharjee.me/about/)"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
