# Site settings
title: bytehead
email: abhishek.bhattacharjee11@gmail.com
description: "It's my side of the internet! I write about stuffs I work on."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
